config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'cars#index'

  resources :cars

  resources :dealerships do
    resources :cars
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dealerships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :dealership

  validates_presence_of :brand, :model, :year, :price
  validates_numericality_of :price, greater_than: 0
end

app/models/dealership.rb
class Dealership < ApplicationRecord
  belongs_to :admin

  has_many :cars

  validates_presence_of :name, :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path if resource.is_a? User

    dealerships_path
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_dealership, only: %i[ new create edit ]
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = @dealership.cars.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = @dealership.cars.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to dealership_path(@dealership), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to dealership_path(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(car_params[:dealership_id])
    end

    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      begin
        params.require(:car).permit(:brand, :model, :year, :price, :dealership_id)
      rescue
        params.permit(:dealership_id)
      end
    end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_dealership, only: %i[ show edit update destroy ]

  # GET /dealerships or /dealerships.json
  def index
    @dealerships = current_admin.dealerships.all
  end

  # GET /dealerships/1 or /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = current_admin.dealerships.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships or /dealerships.json
  def create
    @dealership = current_admin.dealerships.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: "Dealership was successfully created." }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1 or /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: "Dealership was successfully updated." }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1 or /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: "Dealership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = current_admin.dealerships.find(params[:id].to_i)
    end

    # Only allow a list of trusted parameters through.
    def dealership_params
      params.require(:dealership).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_price(price)
    "$ #{price}"
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :dealership_id %>
    <%= form.select :dealership_id, Dealership.all.map{ |d| [d.name, d.id] }%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Year</th>
      <th>Price</th>
      <th>Dealership</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.price %></td>
        <td><%= car.dealership_id %></td>
        <td><%= link_to 'Show', car %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Dealership:</strong>
  <%= @car.dealership_id %>
</p>

<%= link_to 'Back', cars_path %>

app/views/dealerships/_form.html.erb
<%= form_with(model: dealership) do |form| %>
  <% if dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
        <% dealership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form', dealership: @dealership %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dealerships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.name %></td>
        <td><%= dealership.address %></td>
        <td><%= link_to 'Show', dealership %></td>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

<%= render 'form', dealership: @dealership %>

<%= link_to 'Back', dealerships_path %>

app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dealership Name:</strong>
  <%= @dealership.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @dealership.address %>
</p>
<hr>

<h4>Cars</h4>

<% @dealership.cars.each do |car| %>
  <p>
    <%= link_to dealership_car_path(@dealership, car) do %>
      <strong>Model:</strong>
      <%= car.model %>
    <% end %>
  </p>
  <p>
    <strong>Brand:</strong>
    <%= car.brand %>
  </p>
  <p>
    <strong>Year:</strong>
    <%= car.year %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= formatted_price(car.price) %>
  </p>
  <hr>
<% end %>

<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %> |
<%= link_to 'New Car', new_dealership_car_path(@dealership) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarInventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% end %>
    <% if admin_signed_in? %>
      <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>